add htlc to fabtoken driver
hyperledger-labs/fabric-token-sdk pull request #279
Opened 2022-07-05 06:51 UTC by HagarMeir

Signed-off-by: Hagar Meir <hagar.meir@ibm.com>

2022-07-05 06:52 UTC, HagarMeir commented
https://github.com/hyperledger-labs/fabric-token-sdk/issues/255

2022-07-05 09:22 UTC, KElkhiyaoui requested changes

2022-07-05 09:22 UTC, KElkhiyaoui commented on token/core/fabtoken/sender.go
> +					return nil, nil, errors.Errorf("failed to unmarshal RawOwner as a exchange script")
as an exchange script

2022-07-05 09:22 UTC, KElkhiyaoui commented on token/services/interop/exchange/wallet.go
> +func (w *OwnerWallet) ListExpired() ([]*token2.UnspentToken, error) {
add comment here.

2022-07-05 09:22 UTC, KElkhiyaoui commented on token/services/interop/exchange/wallet.go
> +func (w *OwnerWallet) ListByPreImage(preImage []byte) ([]*token2.UnspentToken, error) {
add comment to method

2022-07-06 09:50 UTC, mbrandenburger commented on token/services/interop/exchange/wallet.go
> +			)
@adecaro this is a good example where we would like to use `if logger.IsEnabledFor(zapcore.DebugLevel)` to prevent unnecessary base64 encoding.

2022-07-10 09:52 UTC, closed without merging