check public parameters match
hyperledger-labs/fabric-token-sdk pull request #368
Opened 2022-08-28 11:15 UTC by adecaro

This PR adds a new check to the fungible integration test. Namely, the check verifies that the public parameters used by the FSC nodes matches those stored at the backend.

Signed-off-by: Angelo De Caro <adc@zurich.ibm.com>

2022-08-31 12:55 UTC, KElkhiyaoui commented on token/core/fabtoken/driver/driver.go
>  		return nil, errors.WithMessage(err, "failed to fetch public parameters")
failed to fetch and update

2022-08-31 12:57 UTC, KElkhiyaoui commented on token/core/fabtoken/loaders.go
> +// Fetch fetches the public parameters from the remote repository
what a remote repository?

2022-08-31 12:58 UTC, KElkhiyaoui commented on token/core/fabtoken/loaders.go
> +// FetchParams fetches the public parameters from the remote repository and unmarshal them
what remote repository?

2022-08-31 12:59 UTC, KElkhiyaoui commented on token/core/fabtoken/ppm.go
> +// Fetch fetches the public parameters from the backed
the backend

2022-08-31 12:59 UTC, KElkhiyaoui commented on token/core/fabtoken/service.go
add comments to interface

2022-08-31 13:00 UTC, KElkhiyaoui commented on token/core/zkatdlog/crypto/ppm/ppm.go
> +
add comments to interface

2022-08-31 13:00 UTC, KElkhiyaoui commented on token/core/zkatdlog/crypto/ppm/ppm.go
>  		return errors.WithMessagef(err, "failed force fetching public parameters")
failed updating

2022-08-31 13:06 UTC, KElkhiyaoui commented on token/core/zkatdlog/nogh/loaders.go
> +// Fetch fetches the public parameters from the backed
from the backend

2022-08-31 13:07 UTC, KElkhiyaoui commented on token/core/zkatdlog/nogh/loaders.go
> +// FetchParams fetches the public parameters from the backed and unmarshals them
from the backend

2022-08-31 13:09 UTC, KElkhiyaoui commented on token/publicparams.go
> +// Update fetches the public parameters from the backend and update the local one accordingly
the local ones

2022-08-31 13:10 UTC, KElkhiyaoui requested changes
please address comments.

2022-09-02 05:57 UTC, adecaro commented
Hi @KElkhiyaoui , please, could you push the changes directly so that we can merge this? 😃

2022-09-02 11:29 UTC, KElkhiyaoui approved these changes
looks good to me

2022-09-02 11:31 UTC, merged