checks and recovery functions
hyperledger-labs/fabric-token-sdk pull request #792
Opened 2024-12-06 05:39 UTC by adecaro

2024-12-11 12:58 UTC, alexandrosfilios reviewed
Some comments to consider

2024-12-11 12:58 UTC, alexandrosfilios commented on token/services/network/orion/tokenfetcher.go
> +	resBoxed, err := f.viewManager.InitiateView(NewRequestQueryTokensView(f.network, namespace, IDs), context)
But I see that we call a responder view on the custodian. We don't have a way to call services through sessions, right?

2024-12-11 13:20 UTC, adecaro commented on token/sdk/db/checks.go
> +func NewOwnerCheckServiceProvider(in struct {
okay

2024-12-11 13:25 UTC, adecaro commented on token/sdk/dig/sdk.go
> +		p.Container().Provide(digutils.Identity[*db.AuditorCheckServiceProvider](), dig.As(new(auditor.CheckServiceProvider))),
to the token-sdk, these are default behaviours that we provide

2024-12-11 13:26 UTC, adecaro commented on token/services/network/fabric/network.go
> +func (n *Network) AreTokensSpent(context context.Context, namespace string, tokenIDs []*token.ID, meta []string) ([]bool, error) {
okay

2024-12-25 17:59 UTC, alexandrosfilios requested changes

2024-12-25 17:59 UTC, alexandrosfilios commented on integration/ports.go
> +		// LibP2PNoReplication,
These need to be activated

2024-12-25 19:57 UTC, alexandrosfilios approved these changes
LGTM

2024-12-26 16:53 UTC, merged