verify #40
hyperledger-labs/fabric-token-sdk pull request #81
Opened 2021-08-19 12:38 UTC by HagarMeir

Signed-off-by: Hagar Meir <hagar.meir@ibm.com>

2021-08-19 14:12 UTC, adecaro requested changes

2021-08-20 08:34 UTC, KElkhiyaoui commented on token/core/fabtoken/validator.go
> +	if inputTokens[0] == nil {
Before checking if the inputTokens[0] is not nil, we should check that len(inputTokens) is not 0.

2021-08-20 08:41 UTC, KElkhiyaoui commented on token/core/fabtoken/validator.go
> +		q, err := token2.ToQuantity(input.Quantity, 64)
We should check that each input is not nil to avoid panic.

2021-08-23 11:53 UTC, KElkhiyaoui requested changes

2021-08-23 11:53 UTC, KElkhiyaoui commented on token/core/fabtoken/validator.go
>  		errors.Errorf("there is no output")
return is missing

2021-08-23 11:53 UTC, KElkhiyaoui commented on token/core/fabtoken/validator.go
> +		errors.Errorf("there is no input")
return is missing

2021-08-23 11:53 UTC, KElkhiyaoui commented on token/core/fabtoken/validator.go
> +		errors.Errorf("first input is nil")
return is missing

2021-08-23 12:55 UTC, KElkhiyaoui approved these changes

2021-08-23 12:56 UTC, KElkhiyaoui approved these changes

2021-08-23 12:57 UTC, KElkhiyaoui approved these changes

2021-08-24 07:55 UTC, adecaro approved these changes

2021-08-24 07:55 UTC, merged