token conversion via issue
hyperledger-labs/fabric-token-sdk pull request #817
Opened 2024-12-27 06:57 UTC by adecaro

2025-01-08 16:20 UTC, alexandrosfilios commented on integration/nwo/token/platform.go
> +	if len(tms.Alias) != 0 {
What does this alias stand for?

2025-01-08 16:22 UTC, alexandrosfilios commented on integration/token/fungible/support.go
> +func GetTMSByAlias(network *integration.Infrastructure, alias string) *topology.TMS {
Maybe it would be better to use a type

```
type Alias string
```
to avoid confusion with the network

2025-01-08 16:54 UTC, alexandrosfilios commented on integration/token/fungible/views/conversion.go
> +		if len(p.Auditor) == 0 {
We don't need to check whether the tx is unspendable here, right?

2025-01-09 06:21 UTC, adecaro commented on integration/token/fungible/views/conversion.go
> +		if len(p.Auditor) == 0 {
you mean the tokens? It is up to the issuer to perform all the checks that are relevant

2025-01-09 06:23 UTC, adecaro commented on integration/nwo/token/platform.go
> +	if len(tms.Alias) != 0 {
it is a way to distinguish two TMSs for the same triplet `network, channel, namespace`. 
In the update integration test, I need to generate different public parameters for the same triplet in order to perform the test. The alias allows me to distinguish them

2025-01-09 06:24 UTC, adecaro commented on integration/token/fungible/support.go
> +func GetTMSByAlias(network *integration.Infrastructure, alias string) *topology.TMS {
okay

2025-01-09 14:27 UTC, alexandrosfilios commented on integration/token/fungible/support.go
> +func Conversion(network *integration.Infrastructure, wpm *WalletManagerProvider, user *token3.NodeReference, wallet string, typ token.Type, auditor *token3.NodeReference, issuer *token3.NodeReference
Maybe convert is very generic. it might create confusion and it might also clash with other possible conversions in the future (e.g. between currencies).

maybe we could call it `upgrade` or `promote`.

2025-01-09 14:30 UTC, alexandrosfilios commented on integration/token/fungible/support.go
> +func Conversion(network *integration.Infrastructure, wpm *WalletManagerProvider, user *token3.NodeReference, wallet string, typ token.Type, auditor *token3.NodeReference, issuer *token3.NodeReference
not very important but instead of passing expectedErrorMsgs I think it makes more sense to pass `errorMatchers ...GomegaMatcher`. This way you can have more complex cases that are needed already in some tests like

```
Equal("..."), Contains("..."), Not(Contains("..."))
```

2025-01-09 15:08 UTC, alexandrosfilios commented on integration/token/fungible/topology/topology.go
> +		tms.Transient = true
What does transient stand for?

2025-01-09 15:37 UTC, alexandrosfilios commented on token/core/zkatdlog/nogh/tokens.go
> +	ok, err := s.CheckConversionProof(utp.Proof, utp.Proof, utp.Tokens)
`utp.Challenge`

2025-01-09 15:46 UTC, alexandrosfilios commented on token/driver/issue.go
> +	TokenConversionRequest *TokenConversionRequest
Maybe we don't have to specify the reason that these tokens are there but the objective. That is, we could call them `TokenRedeemRequest`. The same for the interface `CheckRedeemProof` `GenRedeemProof` etc. This could make this field more versatile for other cases where we redeem some tokens to issue others transactionally (e.g. currency conversion).

2025-01-09 15:55 UTC, alexandrosfilios commented on token/core/zkatdlog/crypto/issue/issue.go
> +	Inputs []*token2.ID
From an interface perspective it would be maybe more clear to have `Inputs` as an aggregation of both id and token
```
Inputs []struct {
 ID *token2.ID
 Token []byte
}
```

2025-01-09 16:00 UTC, alexandrosfilios commented on token/core/zkatdlog/crypto/issue/issue.go
>  // IsGraphHiding returns false, indicating that fabtoken does not hide the transaction graph
Not relevant to this pr but maybe update the token and say "this implementation of zkat" instead of "fabtoken"

2025-01-09 16:07 UTC, alexandrosfilios commented on token/core/zkatdlog/crypto/setup.go
> +	if bitLength > 64 {
Do we need this condition? We make the check in the constructor right?

2025-01-09 16:20 UTC, alexandrosfilios commented on token/core/zkatdlog/nogh/issue.go
> +		if len(tokens) != 0 {
to avoid nesting, we could add this condition to the previous clause
```
if opts != nil && opts.TokenConversionRequest != nil && len(opts.TokenConversionRequest.Tokens) > 0
```

2025-01-09 16:23 UTC, alexandrosfilios commented on token/core/zkatdlog/nogh/tokens.go
> +	fabtoken16Type, err := fabtoken2.SupportedTokenFormat(16)
These can also be defined as constants outside of this method
```
const fabtoken16Type = utils.MustGet(fabtoken2.SupportedTokenFormat(16))
```

2025-01-09 16:29 UTC, alexandrosfilios commented on token/core/zkatdlog/nogh/tokens.go
> +	fabtoken16Type, err := fabtoken2.SupportedTokenFormat(16)
Is this supposed to be fabtoken? I think the format for zkat was comm.

2025-01-09 16:31 UTC, alexandrosfilios commented on token/driver/request.go
> +			TokenIDs[j].Index = int(tokenID.Index)
Is there a problem with the serialization of uint64?

2025-01-09 16:42 UTC, alexandrosfilios commented on token/services/db/sql/common/tokens.go
> +		Spendable:          driver.Any,
For the sake of completeness if we're querying all unspendable tokens with this walletID and tokenType the condition should be

```
WHERE wallet_id = ... AND token_type = ... AND (spendable == true OR format IN (...))
```
Otherwise maybe we could rename this method to `UnspendableFormatTokensIteratorBy`

2025-01-09 16:46 UTC, alexandrosfilios commented on token/services/db/sql/common/tokens.go
> +		for _, t := range supportedFormats {
We can either use `slices.Contains(supportedFormats, token.Format(tmp))` or (in case we expected there to be many supported formats) use
```
supportedFormats collection.Set[token.Format]
```
and then `supportedFormats.Contains(token.Format(tmp))`

2025-01-09 16:51 UTC, alexandrosfilios commented on token/services/identity/common/lm.go
> +		identity, _, err := keyManager.Identity(nil)
```
if identity, _, err := keyManager.Identity(nil); err != nil {
 return err
} else if found := slices.ContainsFunc(l.targetIdentities, identity.Equal); !found {
 return nil
}
```

2025-01-09 16:54 UTC, alexandrosfilios commented on token/services/identity/common/lm.go
> +		identity, _, err := keyManager.Identity(nil)
A bit more concise and less nesting:
```
if _, ok := l.localIdentitiesByName[config.ID]; !ok || keyManager.Anonymous() || len(l.targetIdentities) == 0 {
 logger.Debugf("no check")
} else if identity, _, err := keyManager.Identity(nil); err != nil {
 return err
} else if found := slices.ContainsFunc(l.targetIdentities, identity.Equal); !found {
 return nil
}
```

2025-01-09 16:57 UTC, alexandrosfilios commented on token/services/ttx/convert.go
> +	TokenType    string
`token.Type`

2025-01-09 17:00 UTC, alexandrosfilios commented on token/services/ttx/convert.go
> +func (r *ConversionInitiatorView) WithWallet(wallet string) *ConversionInitiatorView {
It is a bit confusing to have two strategies to pass arguments: `With...` and passing them to the constructor. We could either have `opts` or pass them directly. In any case I would force to pass them on instantiation to enforce immutability. Otherwise one might think that WithWallet is meant to be called also after instantiation.

2025-01-09 17:01 UTC, alexandrosfilios commented on token/services/ttx/convert.go
> +func (r *ConversionInitiatorView) getRecipientIdentity(context view.Context) (*token.TMSID, view.Identity, []byte, []byte, error) {
Maybe rename this method. Or otherwise inline it. Its logic is pretty straightforward and it has too many outputs.

2025-01-09 17:04 UTC, alexandrosfilios requested changes
Comments to address

2025-01-10 06:20 UTC, adecaro commented on integration/token/fungible/support.go
> +			tms = TMS
okay

2025-01-10 06:22 UTC, adecaro commented on integration/token/fungible/topology/topology.go
> +		tms.Transient = true
I'll add a comment, but it means that it is not an actual TMS, it is a TMS for which we need to generate only the public parameters

2025-01-10 06:25 UTC, adecaro commented on token/core/zkatdlog/nogh/tokens.go
> +	ok, err := s.CheckConversionProof(utp.Proof, utp.Proof, utp.Tokens)
I'll introduce types to avoid this issue

2025-01-10 06:28 UTC, adecaro commented on token/driver/issue.go
> +	TokenConversionRequest *TokenConversionRequest
in this case, I think it is better to clarify the reason to avoid confusion. Different operations might have different requirements. Better to explicitly differentiate.

2025-01-10 06:36 UTC, adecaro commented on token/services/ttx/convert.go
> +	TokenType    string
okay

2025-01-10 06:37 UTC, adecaro commented on token/services/ttx/convert.go
> +func (r *ConversionInitiatorView) WithWallet(wallet string) *ConversionInitiatorView {
indeed, they can also after initialization

2025-01-10 06:37 UTC, adecaro commented on token/services/ttx/convert.go
> +func (r *ConversionInitiatorView) getRecipientIdentity(context view.Context) (*token.TMSID, view.Identity, []byte, []byte, error) {
but inlining makes the calling method bigger, no?

2025-01-10 06:48 UTC, adecaro commented on token/services/db/sql/common/tokens.go
> +		var tmp string
there is already a var with that name after...

2025-01-10 06:50 UTC, adecaro commented on token/services/db/sql/common/tokens.go
> +		for _, t := range supportedFormats {
okay

2025-01-10 06:57 UTC, adecaro commented on token/driver/request.go
> +			TokenIDs[j].Index = int(tokenID.Index)
yes, asn1 does not support it

2025-01-10 06:58 UTC, adecaro commented on token/core/zkatdlog/nogh/tokens.go
> +	fabtoken16Type, err := fabtoken2.SupportedTokenFormat(16)
the dlog driver supports the conversion from fabtoken, it might support more. To arrive later.

2025-01-10 06:59 UTC, adecaro commented on token/core/zkatdlog/nogh/issue.go
> +		if len(tokens) != 0 {
okay

2025-01-10 07:00 UTC, adecaro commented on token/core/zkatdlog/crypto/issue/issue.go
>  // IsGraphHiding returns false, indicating that fabtoken does not hide the transaction graph
okay

2025-01-10 07:13 UTC, alexandrosfilios commented on token/services/ttx/convert.go
> +func (r *ConversionInitiatorView) getRecipientIdentity(context view.Context) (*token.TMSID, view.Identity, []byte, []byte, error) {
It's a matter of taste. They are simple calls in this method without any data calculations. If they had more calculations that all produce one result, I would definitely extract them. But still whatever is better for you. In this case we can just rename this method to reflect what it gets.

2025-01-10 07:19 UTC, adecaro commented on token/core/zkatdlog/crypto/issue/issue.go
> +	Inputs []*token2.ID
okay

2025-01-10 10:06 UTC, adecaro commented on integration/token/fungible/support.go
> +func Conversion(network *integration.Infrastructure, wpm *WalletManagerProvider, user *token3.NodeReference, wallet string, typ token.Type, auditor *token3.NodeReference, issuer *token3.NodeReference
went for `upgrade`

2025-01-11 17:25 UTC, alexandrosfilios commented on token/core/zkatdlog/nogh/issue.go
> +		tokens := opts.TokenConversionRequest.Tokens
TokenConversionRequest we can rename as well

2025-01-11 17:25 UTC, alexandrosfilios commented on token/core/zkatdlog/nogh/tokens.go
> +func (s *TokensService) ProcessTokenConversionRequest(utp *driver.TokenConversionRequest) ([]token.Type, []uint64, error) {
Upgrade

2025-01-11 17:27 UTC, alexandrosfilios commented on token/request.go
> +func (r *Request) Convert(
Upgrade

2025-01-12 10:58 UTC, alexandrosfilios approved these changes
LGTM

2025-01-12 16:18 UTC, merged